#! /opt/ast/bin/ksh

POLICYDIR=/opt/ECSpooler/systrace-policy
INTERPRETER=/usr/pkg/java/sun-1.5/bin/java

POLICYFILE=${INTERPRETER//\//_}
POLICYFILE=${POLICYFILE/_}
if [[ -r $POLICYFILE ]]; then
   PATH=/usr/pkg/java/sun-1.5/bin:${PATH}; export PATH
   JAVA_HOME=/usr/pkg/java/sun-1.5; export JAVA_HOME
   JVM_HOME=/usr/pkg/java/sun-1.5; export JVM_HOME
   ulimit -d `ulimit -H -d`

   trap 'kill $! && trap - TERM && kill $$' TERM

   systrace -a -d $POLICYDIR $INTERPRETER "$@" &
   wait %%
else
   print "Internal error: Policy file not readable.  Please contact your tutor."
   exit 1
fi
