#! /opt/ast/bin/ksh

#JAVA_HOME=/opt/diablo-jdk1.5.0_07;	export JAVA_HOME
JAVA_HOME=/usr/pkg/java/sun-1.5;  	export JAVA_HOME
JVM_HOME=${JAVA_HOME};			export JVM_HOME
PATH=${JAVA_HOME}/bin:${PATH};		export PATH

ulimit -d `ulimit -H -d`
${JAVA_HOME}/bin/javac -encoding utf-8 "$@"
