#! /opt/ast/bin/ksh

#JAVA_HOME=/opt/diablo-jdk1.5.0_07;	export JAVA_HOME
JAVA_HOME=/usr/pkg/java/sun-1.5;	export JAVA_HOME
JVM_HOME=${JAVA_HOME};			export JVM_HOME
PATH=${JAVA_HOME}/bin:${PATH};		export PATH
INTERPRETER=${JAVA_HOME}/bin/java

ulimit -d `ulimit -H -d`

trap 'kill $! && trap - TERM && kill $$' TERM

$INTERPRETER "$@" &
wait %%
