#! /opt/ast/bin/ksh

OP=$(/opt/swi-prolog-5.6.24/bin/pl -q -f none -s "$@" < /dev/null 2>&1)
ERR=$?

echo "$OP"

if [ $ERR -ne 0 ]
then
  exit $ERR
else
  if echo "$OP" | grep '^ERROR' -q
  then
    exit 1
  else
    exit 0
  fi
fi
